<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SbConsole.Core\SbConsole.Core.csproj" />
    <ProjectReference Include="..\SbConsole.Sdk\SbConsole.Sdk.csproj" />
    <ProjectReference Include="..\Plugins\SbConsole.Plugins.ServiceBus\SbConsole.Plugins.ServiceBus.csproj" />
    <ProjectReference Include="..\Plugins\SbConsole.Plugins.Kafka\SbConsole.Plugins.Kafka.csproj" />
    <ProjectReference Include="..\Plugins\SbConsole.Plugins.Aws\SbConsole.Plugins.Aws.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.9.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
